# Form implementation generated from reading ui file 'app/ui/local_profile_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from app.widgets.cancel_cross_button import CancelCrossButton
from app.widgets.save_button import SaveButton
from app.widgets.trash_bin_button import TrashBinButton


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1529, 803)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_cross_button = CancelCrossButton(
            'app/assets/cancel_cross_light.svg',
            'app/assets/cancel_cross_dark.svg',
            parent=Form
        )
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_cross_button.sizePolicy().hasHeightForWidth())
        self.cancel_cross_button.setSizePolicy(sizePolicy)
        self.cancel_cross_button.setMinimumSize(QtCore.QSize(90, 90))
        self.cancel_cross_button.setText("")
        self.cancel_cross_button.setIconSize(QtCore.QSize(90, 90))
        self.cancel_cross_button.setFlat(True)
        self.horizontalLayout.addWidget(self.cancel_cross_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.save_button = SaveButton(
            'app/assets/save_light.svg',
            'app/assets/save_dark.svg',
            parent=Form
        )
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(90, 90))
        self.save_button.setText("")
        self.save_button.setIconSize(QtCore.QSize(90, 90))
        self.save_button.setFlat(True)
        self.horizontalLayout.addWidget(self.save_button)

        self.trash_bin_button = TrashBinButton(
            'app/assets/trash_bin_light.svg',
            'app/assets/trash_bin_dark.svg',
            parent=Form
        )
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trash_bin_button.sizePolicy().hasHeightForWidth())
        self.trash_bin_button.setSizePolicy(sizePolicy)
        self.trash_bin_button.setMinimumSize(QtCore.QSize(90, 90))
        self.trash_bin_button.setSizeIncrement(QtCore.QSize(5, 5))
        self.trash_bin_button.setText("")
        self.trash_bin_button.setIconSize(QtCore.QSize(90, 90))
        self.trash_bin_button.setFlat(True)
        self.trash_bin_button.setObjectName("trash_bin_button")
        self.horizontalLayout.addWidget(self.trash_bin_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 245, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 319, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.addButton(self.cancel_cross_button)
        self.buttonGroup.addButton(self.save_button)
        self.buttonGroup.addButton(self.trash_bin_button)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Local Profile Page"))
