# Form implementation generated from reading ui file 'app/ui/text_area.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setBaseSize(QtCore.QSize(1200, 800))
        Form.setStyleSheet("background: rgb(0, 255, 0)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 317, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_row_display = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.first_row_display.setFont(font)
        self.first_row_display.setText("")
        self.first_row_display.setObjectName("first_row_display")
        self.verticalLayout.addWidget(self.first_row_display)
        self.second_row_display = QtWidgets.QLabel(parent=Form)
        self.second_row_display.setMaximumSize(QtCore.QSize(16777215, 800))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.second_row_display.setFont(font)
        self.second_row_display.setText("")
        self.second_row_display.setObjectName("second_row_display")
        self.verticalLayout.addWidget(self.second_row_display)
        self.third_row_display = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.third_row_display.setFont(font)
        self.third_row_display.setText("")
        self.third_row_display.setObjectName("third_row_display")
        self.verticalLayout.addWidget(self.third_row_display)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 316, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tex Area"))
